### ISSUE TITLE
Send a notification email to admins when there are new registrations. 

### ISSUE THREAD

**Issue by benevbright** [nishi-ai/softball-register-server#35]
It's important to know as quickly as possible if there is a new registration. 
So we can send the invitation to them. 

So as an admin, I like to get an email when there are new registrations. 
Admin: @benevbright and @nishi-ai 

There are many ways to send an email from node js. Searching with "nodejs send email" would be a good start.

**Comment by nishi-ai** [comment]
@benevbright 
Appearently, sendgrid offers free sending email, as long as we won't get 100 emails/day.

**Comment by benevbright** [comment]
<img width="591" alt="Screenshot 2022-03-19 at 11 03 05" src="https://user-images.githubusercontent.com/916690/159116710-4af26857-c851-4fe8-8720-0aadf97763c5.png">

The email is sent!! amazing. 

but it goes to the spam folder lol. Maybe it's due to the mail title, which looks super spammy 😁
